### ISSUE TITLE
Ingenico ipp320 support

### ISSUE THREAD

**Issue by evgenmedia** [F4pl0/ingenico-pos-dotnet-lib#2]
Hello!

Does this solution supports ipp320 terminal?

**Comment by F4pl0** [comment]
Haven't tested it on the ipp-320 yet. It might work.
This is just a "heads up" code, because Ingenico has documented their protocol very poorly, also it's a bit confusing so this library should sort out the confusing part, define few constants, parse out the messages (Update comming very soon) and just enable dazzle-free communication with the POS Terminal. Current Version (1.0.1) is just a beginning of the development, since it has a long way to go, but getting there.

**Comment by F4pl0** [comment]
I'm working by the Serbian version of ECR - POS Communications protocol documentation. It should be the same and universal for all of the Asseco/Ingenico devices. I'm working with very limited information and WITHOUT Asseco group/Ingenico support (for now, Ingenico *wink wink* ), so I test it on whatever I can lay my hands on, and for now it was the iCT-220.

**Comment by F4pl0** [comment]
In conclusion - **It should**
Please let me know if you manage to test it. Thanks.
